services:
  database:
    container_name: comunica_db_dev
    image: postgres:16.9
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: comunicadb
    ports:
      - "5432:5432"
    volumes:
      - comunicadb_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d comunicadb"]
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - comunica-api-network

  api:
    container_name: comunica_api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:pwd123@database:5432/comunicadb
      - JWT_SECRET="segredo-de-teste-jwt"
      - LOG_LEVEL=info
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,https://seu-front.com
      - HOST=0.0.0.0
      - PORT=3000
   
    restart: on-failure
    networks:
      - comunica-api-network

volumes:
   comunicadb_data:
    name: comunicadb_data_dev

networks:
  comunica-api-network:
    driver: bridge