module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/*.test.ts"],
  moduleNameMapper: {
    "^@src/(.*)$": "<rootDir>/src/$1",
    "^@configs/(.*)$": "<rootDir>/src/lib/configs/$1",
    "^@shared/(.*)$": "<rootDir>/src/shared/$1",
    "^@middlewares/(.*)$": "<rootDir>/src/shared/middlewares/$1",
    "^@auth/(.*)$": "<rootDir>/src/modules/auth/$1",
    "^@integrations/(.*)$": "<rootDir>/src/modules/integrations/$1",
    "^@announcements/(.*)$": "<rootDir>/src/modules/announcements/$1",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  testTimeout: 15000,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  // collectCoverageFrom: [
  //   "src/**/*.ts",
  //   "!src/**/*.d.ts",
  //   "!src/**/*.schema.ts",
  //   "!src/**/*.dto.ts",
  //   "!src/**/*.interfaces.ts",
  //   "!src/lib/configs/**/*.ts",
  //   "!src/server.ts",
  //   "!src/app.ts",
  //   "!src/modules/**/index.ts",
  //   "!src/modules/**/*.module.ts",
  //   "!src/shared/handlers/**/*.ts",
  //   "!src/shared/helpers/**/*.ts",
  // ],
};
